### ISSUE TITLE
Highlights Retrieve Links Error

### ISSUE THREAD

**Issue by jumoog** [Hashirama/OFDL#1]
Happens with one Model while getting Highlights

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "OFDL.py", line 397, in Get_Links
>     self.onlyfans.get_links(dict_return, value, index)
>   File "/home/OFDL/OFDL/module/OF.py", line 287, in get_links
>     filename = link["source"].split('/')[-1]
> KeyError: 'source'

**Comment by pbradjr99** [comment]
I get almost the same error message when retrieving the Messages from some Models
![Snap1](https://user-images.githubusercontent.com/13079644/75616990-a5a55600-5b0d-11ea-92d0-8ecc9465f9bc.png)

**Comment by Hashirama** [comment]
> Happens with one Model while getting Highlights
> 
> > Exception in thread Thread-1:
> > Traceback (most recent call last):
> > File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> > self.run()
> > File "/usr/lib/python3.8/threading.py", line 870, in run
> > self._target(*self._args, **self._kwargs)
> > File "OFDL.py", line 397, in Get_Links
> > self.onlyfans.get_links(dict_return, value, index)
> > File "/home/OFDL/OFDL/module/OF.py", line 287, in get_links
> > filename = link["source"].split('/')[-1]
> > KeyError: 'source'

Yeah I didn't error check properly, sorry. I'll update it

**Comment by jumoog** [comment]
if i change
`        self.links += stories + highlights + images + videos + audio`
to
`        self.links += highlights + images + videos + audio`
i can download hightlights

**Comment by Hashirama** [comment]
> if i change
> ` self.links += stories + highlights + images + videos + audio`
> to
> ` self.links += highlights + images + videos + audio`
> i can download hightlights

Yeah I just realised that now haha

**Comment by Hashirama** [comment]
> I get almost the same error message when retrieving the Messages from some Models
> ![Snap1](https://user-images.githubusercontent.com/13079644/75616990-a5a55600-5b0d-11ea-92d0-8ecc9465f9bc.png)

For your issue, the file isn't being found and I know why.

I'll release an update.
