### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by ThailandTony** [Hashirama/OFDL#10]
Hi
Upto  2 days ago this was working fine Now I'm getting 

Login failed
b'{"error":{"code":401,"message":"Request sign required"}}'

I've tried several attempt including in Chrome Logging out of OF clearing cache and login in again 
Then rentering fresh cookie / user agent 

BTW: During login I had to verify not a robot

Is this  user error, EG me doing something wrong  or is there a problem?

 Thanx

**Comment by Hashirama** [comment]
What version are you using?

On 29 Jul 2020, at 17:48, ThailandTony <notifications@github.com> wrote:

﻿

Hi
Upto 2 days ago this was working fine Now I'm getting

Login failed
b'{"error":{"code":401,"message":"Request sign required"}}'

I've tried several attempt including in Chrome Logging out of OF clearing cache and login in again
Then rentering fresh cookie / user agent

BTW: During login I had to verify not a robot

Is this user error, EG me doing something wrong or is there a problem?

Thanx

**Comment by ThailandTony** [comment]
Not sure 
No version number in readme  or OFDLv2.py

It was DL on 16th June 2020

**Comment by Hashirama** [comment]
There's a new version, 2.2. Use that one. I just tested it.
