### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by 1quantum1** [Hashirama/OFDL#16]
Old version was working fine last time I used it. Today tried to use it, keep getting:
Login failed
b'{"error":{"code":0,"message":"Access denied."}}'

Just installed version 2.2 and get the same thing.

According to the README file, I copy the underlined info as shown below: (I accidentally edited out the sess id, but I assure its included in the string
![cookie](https://user-images.githubusercontent.com/74433323/99126097-7b2ff600-25d3-11eb-8a03-fa8c2c641410.jpg)

When that information is entered, you can see login failed:
![ofdl](https://user-images.githubusercontent.com/74433323/99126332-f2fe2080-25d3-11eb-8462-783c01983c7c.png)

**Comment by Hashirama** [comment]
I didn't see this until now, is it still not working? and when did you last use it?

**Comment by jumoog** [comment]
you are sure you are still on Firefox 81? With a new Firefox Version you have to change the User Agent and the Cookie Value.

**Comment by 1quantum1** [comment]
> you are sure you are still on Firefox 81? With a new Firefox Version you have to change the User Agent and the Cookie Value.

You're right.. that was the issue smh.. I had changed my user agent and forgot to switch it back

**Comment by 1quantum1** [comment]
> I didn't see this until now, is it still not working? and when did you last use it?

Issue was with my User Agent... everything is working fine now
