### ISSUE TITLE
Subscriptions not showing up

### ISSUE THREAD

**Issue by cerberusflame99** [Hashirama/OFDL#23]
I've been using this program for quite a while but it seems after entering my cookie and user agent, my subscriptions dont show up anymore. Iver reentered the information multiple times to no avail. If this project is still active, please look into this

**Comment by cerberusflame99** [comment]
to add to this, i am now getting an error message on console. 
`Login failed
b'{"error":{"code":0,"message":"Access denied."}}'`

**Comment by lalenguanegra** [comment]
You need to provide a new value for cookie + user agent
when you log out, from the web browser, the cookie + user agent value will no longer work.
