### ISSUE TITLE
Won't login

### ISSUE THREAD

**Issue by swearfu** [Hashirama/OFDL#24]
No matter how many times I set the cookie and the user-agent, I get the same error (see below). It's been working for a long time, so my guess is OF changed something.

Login failed
b'{"error":{"code":401,"message":"Please refresh the page"}}'

**Comment by simonrule** [comment]
same here

**Comment by ostatnichoroszczanin** [comment]
same. Please update this great app

**Comment by pbradjr99** [comment]
yep still not working

**Comment by pbradjr99** [comment]
Guess we're not getting a fix for this program, it was good while it lasted, thanks! Anyway, what have you guys been using since it went down??

**Comment by cjb900** [comment]
i've switched to using https://github.com/DIGITALCRIMINAL/OnlyFans. There is no GUI version but it is contently being updated to work with onlyfans

**Comment by raggabrashtrout** [comment]
Same here  
It looks like OF has changed  it's cookie  I suspect this is why auth is failing

DIGITALCRIMINAL/OnlyFans.  Seems to has changed it auth method it now allows you to use email + password
Which is simpler  and therefore less prone to error

**Comment by pbradjr99** [comment]
I could never get DIGITALCRIMINAL/OnlyFans to work so much harder than this program. I guess until you get used to how it works. If anyone wants to show me how to use it let me know, thanks. email is pbradjr@gmail.com
