### ISSUE TITLE
Does not grab all links / download all media

### ISSUE THREAD

**Issue by Kicnk** [Hashirama/OFDL#25]
Does not grab all links / download all media, **but less than half of them.** 

For instance, on one subscription the **General tab states correctly that the model has 75 photos and 54 videos, 129 in total.** But after grabing the links, the Links tab lists a much shorter list than that and same goes to Download tab after pressing the Download Files -button on the previous tab. **As a result, only 29 videos and 33 photos were downloaded, 62 in total.**

Another example: **General tab states correctly 304 photos and 62 videos, 366 in total.**  Again Links tab lists a lot less than that and same goes to Download tab. **As a result, only 120 photos and 39 videos were downloaded, 159 in total.**

As a potentially related note, there are number of errors _"QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)"_ when fetching information about the subscriptions as well as (sometimes) when fetching the links from a subscription.

**Comment by Hashirama** [comment]
Some content can be hidden behind paywalls and that could be why there is a difference in the amount displayed and downloaded.
