### ISSUE TITLE
I don't know if it's because the amount of data is too large or because the script has errors

### ISSUE THREAD

**Issue by belthil17** [Hashirama/OFDL#29]
![image](https://user-images.githubusercontent.com/52347608/195995480-70e1d3ad-8536-4339-abb3-b70503bfacda.png)

**Comment by JuseCub** [comment]
![Screenshot 2022-10-27 17 41 39](https://user-images.githubusercontent.com/116849878/198412200-97c4d81d-2c47-4f09-8584-5130282381f3.png)


Same issue. Tried on a very large profile but also on a much smaller one.

**Comment by Hashirama** [comment]
It was an issue with the code. Either I didn't test properly, or they made a change on the site.

Either way its been fixed. Sorry.
